# -*- coding: utf-8 -*-
"""AI-Practical1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L2-9Rlbh6Z0jxFYfcaBc3GVrvB9jsB4C
"""

print("hello i am python")
print("today we will build a cleaning robot together")
print(2+3,"is the answerto 2+3")
# this is our room: 5 sports. D=dirty,c=clean
room=["D","C","D","D","C"]

# A helper that draws the room with nice symbols
def show_room(room):
  picture=""
  for spot in room:
    if spot=="D":
        picture +="" #dirty spot
    else:
        picture +="" #clean spot
  print(picture)

print("our room right now")
show_room(room)

# the robot looks at one spot and decides what to do.
def clean_spot(spot):
    if spot=="D": # the room is dirty
      # your turn: make it clean. type "c" on the next line,next line replacing the word here
      return "C"

    else: #the room is cleaned already
      return "c"
result=clean_spot("D")
print(" The robot looked at a dirty spot and made it: ",result," (C means clean)")
print("BEFORE - the dirty room:")
def show_room(room):
  print(room)

for i in range(len(room)):
  room[i]=clean_spot(room[i])
  print("after cleaning spot number",i+1,":")
  show_room(room)

  print()
  print("after - all done!")
  show_room(room)

print("Create a 🤖 Chatbot:")

while True:
    user = input("You: ").lower()

    if user == "hi" or user == "hello":
        print("🤖 Chatbot: Hello! How are you?")

    elif "how are you" in user:
        print("🤖 Chatbot: I'm fine, thank you!")

    elif "what is your name" in user:
        print("🤖 Chatbot: My name is Chatbot.")

    elif user == "bye":
        print("🤖 Chatbot: Bye!")
        break

    else:
        print("🤖 Chatbot: I don't understand.")

spam_words = [
    "lottery",
    "claim",
    "click",
    "winner",
    "prize",
    "free",
    "lobbery",
    "money",
]

email = input("Enter your email message:\n")
email = email.lower()

spam = False

for word in spam_words:
    if word in email:
        spam = True
        break

if spam:
    print("\nResult: Spam Mail")
else:
    print("\nResult: Not Spam Mail")