# -*- coding: utf-8 -*-
"""AI -Practical 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cihoph9j6kFrRaowcaD3ZEDPg00kwCnx
"""

map_rooms = {
    "A": ["B","C"],
    "B": ["D"],
    "C": ["D"],
    "D": ["G"],
    "G": [],
}

print("our map:")
print("             A  (Start)")
print("            / \\")
print("           B   C")
print("            \\ /")
print("             D")
print("             -")
print("             G (Tresure )")
print()
print("Doors from each room:", map_rooms)

def bfs(start, goal):
    to_do = [start]
    visited = []
    order = []

    while to_do:
        room = to_do.pop(0)

        if room not in visited:
            visited.append(room)
            order.append(room)

            if room == goal:
                return order

            for nxt in map_rooms[room]:
                to_do.append(nxt)

    return order


order = bfs("A", "G")
print("Bfs checked the rooms in this order:", order)
print("number of rooms Bfs checked:", len(order))

def dfs(start, goal):
    to_do = [start]
    visited = []
    order = []

    while to_do:
        room = to_do.pop()


        if room not in visited:
            visited.append(room)
            order.append(room)

            if room == goal:
                return order

            for nxt in reversed(map_rooms[room]):
                to_do.append(nxt)

    return order

order = dfs("A", "G")
print("Dfs checked the rooms in this order:", order)
print("number of rooms Dfs checked:", len(order))

map_rooms = {
    "A": ["B", "C"],
    "B": ["D"],
    "C": ["D"],
    "D": ["G"],
    "G": [],
}

def dfs(start, goal):
  to_do = [start]
  visited = []
  order = []

  while to_do:
    room = to_do.pop()

    if room in visited:
      continue
    visited.append(room)
    order.append(room)

    if room == goal:
      return order

    for nxt in map_rooms[room]:
        to_do.append(nxt)

  return order

order = dfs("A", "G")
print("DFS checked the rooms in this order:", order)
print("Number of rooms DFS checked:", len(order))

from collections import deque

def find_shortest_path_bfs(start, goal):

    queue = deque([[start]])
    visited = {start}

    while queue:
        path = queue.popleft()
        current_room = path[-1]

        if current_room == goal:
            return path, len(path) - 1

        for neighbor in map_rooms.get(current_room, []):
            if neighbor not in visited:
                visited.add(neighbor)
                new_path = list(path)
                new_path.append(neighbor)
                queue.append(new_path)

    return None, -1


best_path, best_cost = find_shortest_path_bfs("A", "G")

if best_path:
    print(f"The best path from A to G is: {best_path}")
    print(f"The best cost (number of steps) is: {best_cost}")
else:
    print("No path found from A to G.")

def evaluate_specific_path(path, graph):
    if not path or len(path) < 2:
        return False, 0, "Path is too short or empty."

    current_cost = 0
    for i in range(len(path) - 1):
        current_room = path[i]
        next_room = path[i+1]
        if next_room in graph.get(current_room, []):
            current_cost += 1
        else:
            return False, current_cost, f"Invalid transition from {current_room} to {next_room}."
    return True, current_cost, "Valid path."

# Evaluate path A -> B -> D
path_ab_d = ['A', 'B', 'D']
is_valid_ab_d, cost_ab_d, message_ab_d = evaluate_specific_path(path_ab_d, map_rooms)
print(f"Path {path_ab_d}: {message_ab_d} Cost: {cost_ab_d}")

# Evaluate path A -> C -> D
path_ac_d = ['A', 'C', 'D']
is_valid_ac_d, cost_ac_d, message_ac_d = evaluate_specific_path(path_ac_d, map_rooms)
print(f"Path {path_ac_d}: {message_ac_d} Cost: {cost_ac_d}")

door_cost = {
    "A": {"B": 1, "C": 1},
    "B": {"D": 1},
    "C": {"D": 1},
    "D": {"G": 1},
    "G": {}
}

def path_cost(path):
  total = 0
  for i in range(len(path) - 1):
    current_room = path[i]
    next_room = path[i + 1]
    if current_room in door_cost and next_room in door_cost[current_room]:
      total += door_cost[current_room][next_room]
    else:

      return -1
  return total


path1 = ["A","B","D","G"]
path2 = ["A","C","D","G"]

cost1 = path_cost(path1)
cost2 = path_cost(path2)

print(f"Path {path1} cost: {cost1}")
print(f"Path {path2} cost: {cost2}")

best_path = None
best_cost = float('inf')

if cost1 != -1 and (best_path is None or cost1 < best_cost):
    best_path = path1
    best_cost = cost1

if cost2 != -1 and (best_path is None or cost2 < best_cost):
    best_path = path2
    best_cost = cost2


if best_path is not None:
    print(f"\nThe best path from the given options is: {best_path}")
    print(f"The best cost is: {best_cost}")
else:
    print("\nNo valid path found among the given options.")



bfs_order = bfs("A", "G")
dfs_order = dfs("A", "G")

print("\nResults comparing BFS and DFS traversal:")
print("-" * 40)
print(f"Bfs (shortest path discovery) checked: {len(bfs_order)} rooms -> {bfs_order}")
print(f"Dfs (depth-first exploration) checked: {len(dfs_order)} rooms -> {dfs_order}")
print(f"Cheapest path found: {best_path} with cost {best_cost}")
print("-" * 40)
print("What we learned:")

print("* BFS checks the nearest rooms first (spreads out)")
print("* DFS dives deep down one path first")

